### ISSUE TITLE
When I tried to place painting, game crashed

### ISSUE THREAD

**Issue by TechniumUnlimited** [Phrille/Vanilla-Boom#5]
https://pastebin.com/rY8mm3Gp

**Comment by TechniumUnlimited** [comment]
I checked with every painting as well as the blank paintings added by the mod, if you right click on the ground it crashes the game

**Comment by Phrille** [comment]
Yes I found the same issue, this should be fixed later today

**Comment by Phrille** [comment]
Fixed
