### ISSUE TITLE
more configs

### ISSUE THREAD

**Issue by SpGilbert** [Phrille/Vanilla-Boom#8]
Would it be possable to add more configs for a few things mainly the ones listed below?
Item drops and crafting recipes.
such as wither bones
primarine arrows and resorce blocks

**Comment by Phrille** [comment]
These are not things that should go in a config. Recipes and item drops should be handled by datapacks. So if you want to modify loot, make a custom datapack. That is how it supposed to work and if other mods are adding this into their config: they're doing it wrong.
